Enable test to only run which required
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

diff --git a/tasks/coala-checks.yaml b/tasks/coala-checks.yaml
--- a/tasks/coala-checks.yaml
+++ b/tasks/coala-checks.yaml
@@ -31,16 +31,6 @@ spec:
         git fetch origin pull/$(params.pr_number)/head:workbranch
         git checkout workbranch
 
-    - name: set-running-state
-      image: registry.access.redhat.com/ubi8/ubi-minimal
-      script: |
-        cat <<EOF > /workspace/output/pr/status/coala.json
-        {
-          "State": "running",
-          "Label": "thoth-ci/coala-check"
-        }
-        EOF
-
     - name: run-coala
       image: quay.io/thoth-station/thoth-coala:v0.10.2
       resources:
@@ -52,25 +42,27 @@ spec:
           cpu: "1"
       workingDir: /workspace/repo
       script: |
-        set +e
-        out=$(coala --ci 2>&1)
-        exit_code=$?
-        set -e
-        if [[ $exit_code -ne 0 ]]; then
-          code="failure"
-          description="The coala test failed!"
-          # echo "Coala Test failed!" > /workspace/output/pr/comments/new
-          # echo "Logs:" >> /workspace/output/pr/comments/new
-          # echo $out >> /workspace/output/pr/comments/new
-        else
-          code="success"
-          description="The coala test succeeded!"
-        fi
-        cat <<EOF > /workspace/output/pr/status/coala.json
-        {
-          "State": "$code",
-          "Target": "http://tekton-dashboard-tekton-pipelines.apps.thoth01.lab.upshift.rdu2.redhat.com/",
-          "Desc": "$description",
-          "Label": "thoth-ci/coala-check"
-        }
+        if [[ -f .coafile ]]; then
+          set +e
+          out=$(coala --ci 2>&1)
+          exit_code=$?
+          set -e
+          if [[ $exit_code -ne 0 ]]; then
+            code="failure"
+            description="The coala test failed!"
+            # echo "Coala Test failed!" > /workspace/output/pr/comments/new
+            # echo "Logs:" >> /workspace/output/pr/comments/new
+            # echo $out >> /workspace/output/pr/comments/new
+          else
+            code="success"
+            description="The coala test succeeded!"
+          fi
+          cat <<EOF > /workspace/output/pr/status/coala.json
+          {
+            "State": "$code",
+            "Target": "http://tekton-dashboard-tekton-pipelines.apps.thoth01.lab.upshift.rdu2.redhat.com/",
+            "Desc": "$description",
+            "Label": "thoth-ci/coala-check"
+          }
         EOF
+        fi
